[package]
name = "server-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ratatui.workspace = true
russh.workspace = true
sqlx.workspace = true
ssh-core = { path = "../ssh-core" }
state-store = { path = "../state-store" }
tokio.workspace = true
tracing.workspace = true
argon2.workspace = true
password-hash.workspace = true
rand_core.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
chacha20poly1305.workspace = true
base64.workspace = true
futures = "0.3"

[dev-dependencies]
serial_test = "3"
sqlx = { version = "0.8.6", features = ["chrono", "macros", "runtime-tokio", "sqlite"] }
state-store = { path = "../state-store" }
