[package]
name = "tui-core"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
ratatui.workspace = true
rb-types = { path = "../rb-types" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
unicode-width.workspace = true
