[package]
name = "tui-core"
version.workspace = true
edition.workspace = true

[dependencies]
ratatui.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
crossterm = "0.29.0"

[dev-dependencies]
anyhow.workspace = true
