[package]
name = "ssh-core"
version.workspace = true
edition.workspace = true

[features]
forwarding-tests = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
russh.workspace = true
rustix.workspace = true
signal-hook.workspace = true
tokio.workspace = true
tracing.workspace = true
async-trait.workspace = true
