[package]
name = "state-store"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
sqlx.workspace = true
tracing.workspace = true
url.workspace = true
